# Portfolio Configuration
# Edit this file to customize your portfolio content

personal:
  name: "Sherod Taylor"
  title: "Platform Engineering Team Lead @ Bloomberg"
  location: "New York, NY"
  tagline: "Building scalable solutions for complex infrastructure"
  description: "Platform Engineering Team Lead at Bloomberg managing 5 engineers and delivering APIs that serve 9,000+ developers daily. 4+ years in engineering leadership, 12+ years building scalable systems. I excel at translating business needs into technical strategy while developing talent and shipping reliable infrastructure."
  availability:
    status: "Open for new opportunities"
    active: true

contact:
  email: "sherodtaylor@gmail.com"
  website: "https://www.sherodtaylor.dev"
  github: "https://github.com/sherodtaylor"
  linkedin: "https://www.linkedin.com/in/sherodtaylor/"

site:
  title: "Sherod Taylor - Platform Engineering Team Lead @ Bloomberg"
  description: "Sherod Taylor Platform Engineering Team Lead @ Bloomberg with deep technical experience."

hero:
  highlights:
    - name: "Team Management"
      icon: "Users"
      color: "green"
    - name: "Distributed Systems"
      icon: "Server"
      color: "purple"
    - name: "API Architecture"
      icon: "Cog"
      color: "orange"
    - name: "Full-Stack"
      icon: "Code"
      color: "cyan"
    - name: "Leadership"
      icon: "Crown"
      color: "amber"
    - name: "Project Management"
      icon: "Tasks"
      color: "emerald"
    - name: "Product"
      icon: "Box"
      color: "rose"
    - name: "Design"
      icon: "Palette"
      color: "indigo"

skills:
  categories:
    - title: "Frontend Development"
      description: "Building modern, responsive web applications"
      icon: "react"
      color: "from-blue-500/20 to-cyan-500/20"
      experience: "12+ years"
      skills:
        - { name: "React", icon: "react" }
        - { name: "Next.js", icon: "nextjs" }
        - { name: "TypeScript", icon: "typescript" }
        - { name: "Tailwind CSS", icon: "tailwindcss" }
    - title: "Backend Development"
      description: "Scalable server-side architecture and APIs"
      icon: "nodejs"
      color: "from-green-500/20 to-emerald-500/20"
      experience: "12+ years"
      skills:
        - { name: "Node.js", icon: "nodejs" }
        - { name: "TypeScript", icon: "typescript" }
        - { name: "Go", icon: "go" }
        - { name: "Python", icon: "python" }
        - { name: "PostgreSQL", icon: "postgresql" }
        - { name: "GraphQL", icon: "graphql" }
        - { name: "API Integration", icon: "Zap" }
    - title: "DevOps & Infrastructure"
      description: "Cloud infrastructure and deployment automation"
      icon: "docker"
      color: "from-purple-500/20 to-pink-500/20"
      experience: "10+ years"
      skills:
        - { name: "Docker", icon: "docker" }
        - { name: "Git", icon: "git" }
        - { name: "Terraform", icon: "terraform" }
        - { name: "Packer", icon: "packer" }
        - { name: "Proxmox", icon: "proxmox" }
        - { name: "OpenStack", icon: "openstack" }
        - { name: "Networking", icon: "Network" }
        - { name: "TrueNAS", icon: "truenas" }
        - { name: "Kubernetes", icon: "kubernetes" }
    - title: "Leadership & Strategy"
      description: "Team leadership, product management, and design thinking"
      icon: "Crown"
      color: "from-amber-500/20 to-orange-500/20"
      experience: "4+ years"
      skills:
        - { name: "Leadership", icon: "Crown" }
        - { name: "People Management", icon: "Users" }
        - { name: "Project Management", icon: "CheckSquare" }
        - { name: "Product Strategy", icon: "Package" }
        - { name: "Design Thinking", icon: "Palette" }

experience:
  positions:
    - company: "Bloomberg LP"
      company_url: "https://www.bloomberg.com"
      role: "Platform Engineering Team Lead"
      period: "March 2023 - Present"
      location: "New York, NY"
      type: "Full-time"
      logo: "bbg"
      description: "Leading centralized API platform development and managing a 5-engineer team focused on developer tools. Created Bento UI framework using module federation."
      achievements:
        - "Built centralized API platform for Private Cloud infrastructure"
        - "Designed Activity API platform providing infrastructure event visibility"
        - "Created Bento UI framework using module federation"
        - "Managed 5-engineer team focused on developer tools and infrastructure reliability"
      technologies: ["React", "Node.js", "TypeScript", "Kubernetes", "Docker", "Golang", "PostgreSQL", "GraphQL", "OpenStack"]
      color: "from-orange-500/20 to-red-500/20"
    - company: "Bloomberg LP"
      company_url: "https://www.bloomberg.com"
      role: "Senior Software Engineer"
      period: "August 2018 - March 2023"
      location: "New York, NY"
      type: "Full-time"
      logo: "bbg"
      description: "Led data center modernization project and architected full-stack software solutions for Bloomberg infrastructure."
      achievements:
        - "Led data center modernization project"
        - "Built centralized API platform for Private Cloud infrastructure"
        - "Designed Activity API platform providing infrastructure event visibility"
        - "Architected full-stack software solutions for Bloomberg infrastructure"
      technologies: ["Python", "JavaScript", "React", "Node.js", "AWS", "Golang", "PostgreSQL", "GraphQL", "OpenStack"]
      color: "from-orange-500/20 to-red-500/20"
    - company: "Paxos (formerly itBit)"
      company_url: "https://paxos.com"
      role: "Senior Software Engineer"
      period: "April 2015 - August 2018"
      location: "New York, NY"
      type: "Full-time"
      logo: "paxos"
      description: "Led infrastructure modernization and REST API platform development. Designed SWIFT banking system integration and implemented zero downtime deployments."
      achievements:
        - "Completed full Terraform migration of manually deployed systems"
        - "Designed and implemented TLS client certificate authentication"
        - "Led REST API platform development for institutional trading"
        - "Designed SWIFT banking system for institutional trading integration"
        - "Implemented zero downtime deployments using HA Proxy"
        - "Proposed framework using Node.js, React.js, and Flux architecture"
        - "Contributed to becoming second-largest Bitcoin exchange by volume"
      technologies: ["Node.js", "React.js", "Terraform", "Docker", "PostgreSQL"]
      color: "from-blue-500/20 to-indigo-500/20"
    - company: "Madison Reed"
      company_url: "https://www.madison-reed.com"
      role: "Software Engineer"
      period: "September 2013 - May 2015"
      location: "San Francisco, CA"
      type: "Full-time"
      logo: "madison-reed"
      description: "Implemented Redis caching system, developed custom CMS, and led migration from Magento to custom Node.js framework."
      achievements:
        - "Implemented Redis caching system reducing database calls"
        - "Developed custom CMS tailored to company workflow"
        - "Led migration from Magento to custom Node.js order processing framework"
      technologies: ["Node.js", "Redis", "MongoDB", "JavaScript", "CSS"]
      color: "from-pink-500/20 to-rose-500/20"

projects:
  items:
    - name: "Home Lab Infrastructure"
      description: "Production home lab running critical daily services for my household while serving as a real-world testing ground for infrastructure provisioning techniques. What I deploy at work, I validate at home first."
      highlights:
        - "Daily Production Use: Running 10+ services my family depends on - Home Assistant controls our lights and thermostats, TrueNAS stores 8TB of family photos/documents, Immich organizes years of memories with AI facial recognition, Jellyfin streams our media library to every device"
        - "Real Provisioning Practice: Infrastructure as Code using Packer and Terraform means I can rebuild any failed service in minutes - learned this when my media server crashed during movie night. Now every service has automated provisioning pipelines just like production systems at work"
        - "Kubernetes Testing: Deployed local K8s clusters for testing containerized applications and understanding orchestration challenges before production deployments"
        - "AI Experimentation: Leveraging Ollama to self-host LLMs and computer vision models, understanding inference infrastructure requirements and optimizing resource allocation for AI workloads"
      link:
        href: "https://github.com/sherodtaylor/homelab-setup"
        label: "sherodtaylor/homelab-setup"
        is_private: true
      icon: "Server"
      tags: ["Proxmox", "Infrastructure as Code", "Kubernetes", "Home Automation", "Packer", "Terraform"]
    - name: "Dotfiles"
      description: "Maintained comprehensive dotfiles and development environment configurations for consistent, reproducible development setups across multiple systems."
      highlights:
        - "Cross-Platform Configuration: Unified development environment setup for macOS and Linux systems"
        - "Editor Configuration: Advanced Neovim configurations with language servers and productivity enhancements"
      link:
        href: "https://github.com/sherodtaylor/dotfiles"
        label: "sherodtaylor/dotfiles"
        is_private: false
      icon: "Settings"
      tags: ["DevOps", "Automation", "Neovim", "Shell Scripting"]

community:
  title: "Community & Leadership"
  description: "Giving back through mentorship and volunteer work"
  activities:
    - title: "Bloomberg Diversity Interview Prep Bootcamp"
      role: "Volunteer Instructor & Mentor"
      duration: "6-month program"
      type: "Mentorship"
      icon: "GraduationCap"
      color: "from-blue-500/20 to-indigo-500/20"
      description: "A comprehensive bootcamp program designed to train underrepresented candidates for technical interviews through mentoring and hands-on training from Bloomberg engineers. Provides 1:1 guidance, curriculum development, and mock interview preparation."
      achievements:
        - "Designed and delivered Systems Design curriculum"
        - "Took on 1:1 mentee and prepared them for coding interviews"
        - "Provided weekly mock interviews and detailed feedback sessions"
        - "Followed training schedule for 6 months: algos, system design, coding interviews"
    - title: "Bloomberg Community Service Leadership"
      role: "Community Service Leader"
      duration: "Ongoing"
      type: "Volunteer"
      icon: "Heart"
      color: "from-pink-500/20 to-rose-500/20"
      description: "Leading community service initiatives within Bloomberg engineering teams, organizing volunteer activities and coordinating outreach programs to support local NYC communities."
      achievements:
        - "Logged 15+ volunteer hours in past year"
        - "Mobilized multiple engineering teams for community service"
        - "Coordinated homeless aid initiatives and care package distribution"
        - "Organized NYC park cleanup efforts"

sections:
  latest_articles:
    title: "Latest Articles"
    description: "Thoughts on software development, leadership, and technology"
    max_count: 3
